language: node_js
sudo: required
dist: trusty
cache:
  directories:
    - node_modules
node_js:
  - 6
before_script:
  - npm prune
after_script:
  - npm start coverage
after_success:
  - npm start semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
